### ISSUE TITLE
Add UHD-IQA dataset

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [chaofengc/Awesome-Image-Quality-Assessment#11]
Hi @chaofengc!

Could you please our new dataset to this repo?

**Paper link**: [arxiv](https://arxiv.org/abs/2406.17472)
**Dataset name**: UHD-IQA
**Type**: NR
**Published**: ECCVW2024
**Website**: [Project](https://database.mmsp-kn.de/uhd-iqa-benchmark-database.html)
**Images**: 6k
**Annotations**: 20 ratings per image

**Comment by chaofengc** [comment]
Thank you for your information. The dataset has been added: https://github.com/chaofengc/Awesome-Image-Quality-Assessment?tab=readme-ov-file#iqa-datasets

**Comment by LorenzoAgnolucci** [comment]
Thank you very much!
