### ISSUE TITLE
Add a paper

### ISSUE THREAD

**Issue by nhshin-mcl** [chaofengc/Awesome-Image-Quality-Assessment#12]
Hello @chaofengc!

Thank you for all your hard work! Could you add our paper to the repository?

Paper link: [CVF open](https://openaccess.thecvf.com/content/CVPR2024/papers/Shin_Blind_Image_Quality_Assessment_Based_on_Geometric_Order_Learning_CVPR_2024_paper.pdf)
Method: QCN
Type: NR
Published: CVPR2024
Code: [Github](https://github.com/nhshin-mcl/QCN?tab=readme-ov-file)
Keywords: geometric order learning

Thank you for your consideration!

**Comment by chaofengc** [comment]
Thank you for your suggestion! Would you please create a pull request to add the paper? Your contribution would be greatly appreciated and would help improve the project for everyone. Thank you!

**Comment by nhshin-mcl** [comment]
Thank you for your time! I create a pull request to add the paper. Would you please check it? Thank you again!
