### ISSUE TITLE
Adding a paper request.

### ISSUE THREAD

**Issue by chencn2020** [chaofengc/Awesome-Image-Quality-Assessment#14]
Hi, @chaofengc!

Thank you for all your great work! 

Recently, we finish a work about IQA for regions of interest (ROI).
Could you add our paper to the repository?

Paper link: [Arxiv](https://arxiv.org/abs/2411.10161)
Method: SEAGULL
Type: IQA for ROIs
Published: Arxiv
Code: [Github](https://github.com/chencn2020/SEAGULL)
Keywords: Regions of Interest, Fine-grained Assessment

Thank you for your consideration!

**Comment by chaofengc** [comment]
Thank you for your suggestion! Would you please create a pull request to add the paper? Your contribution would be greatly appreciated and would help improve the project for everyone. Thank you!

**Comment by chencn2020** [comment]
Sure, I have created a PR to add the paper.
Would you please check it? Thank you again!

**Comment by chaofengc** [comment]
Thank you so much for your contribution🤗!
