### ISSUE TITLE
Koniq-10k link is invaild

### ISSUE THREAD

**Issue by Cassieyy** [chaofengc/Awesome-Image-Quality-Assessment#4]
hii, the download link of Koniq-10k is invaild(http://projects.dfki.uni-kl.de/yfcc100m/ , http://database.mmsp-kn.de/koniq-10k-database.html) now, could you please provide the vaild one? thanks in advance!!

**Comment by chaofengc** [comment]
I have checked these links and I can still download dataset from the latter link, which contains Koniq10k dataset.
Due to the license problem, I am not authorized to distribute the dataset. Please try to download from the **latter link** by yourself.

**Comment by Cassieyy** [comment]
> I have checked these links and I can still download dataset from the latter link, which contains Koniq10k dataset. Due to the license problem, I am not authorized to distribute the dataset. Please try to download from the **latter link** by yourself.

emm, but i cannot open either link with any network...

**Comment by chaofengc** [comment]
You might need VPN to open the link or try the following link: http://ivc.uwaterloo.ca/database/IQADataset

**Comment by Cassieyy** [comment]
> You might need VPN to open the link or try the following link: http://ivc.uwaterloo.ca/database/IQADataset

It works!!! Thank you for your enthusiastic help.
