### ISSUE TITLE
kind request for adding our NRIQA methods

### ISSUE THREAD

**Issue by Baoliang93** [chaofengc/Awesome-Image-Quality-Assessment#6]
Thanks for your Great Work!

Could you kindly add our NR-IQA works to your collection page? The following is some information,
#1
Type: NRIQA
Name: FPR
Paper(TIP2022): https://doi.org/10.1109/TIP.2022.3205770
Github: https://github.com/Baoliang93/FPR
Keywords:   Mutual learning, pseudo-reference feature

#2
Type: NRIQA
Name: MonotonicIQA
Paper(EL2023):  https://doi.org/10.1049/ell2.12698
Github: https://github.com/fzp0424/MonotonicIQA
Keywords:   Mixed datasets learning, Monotonic regression

**Comment by chaofengc** [comment]
I appreciate your efforts and contributions. The first paper you sent me is very interesting and relevant, so I have added it to the collection. The second paper, however, is more like a short paper, and it has some overlap with [this paper](https://arxiv.org/abs/2011.04263). Therefore, I decided not to include it in the collection. I hope you understand my decision.

**Please note that any direct contributions are welcomed. If you have a paper that you think should be in the collection, please create a pull request and add it yourself. Thank you so much 🤗 !**
