### ISSUE TITLE
Add paper

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [chaofengc/Awesome-Image-Quality-Assessment#7]
Hi @chaofengc!

Thanks for your awesome work! Could you please add our paper to the repo?

- **Paper link**: [arxiv](https://arxiv.org/abs/2310.14918) [CVF open access](https://openaccess.thecvf.com/content/WACV2024/html/Agnolucci_ARNIQA_Learning_Distortion_Manifold_for_Image_Quality_Assessment_WACV_2024_paper.html)
- **Method**: ARNIQA
- **Type**: NR
- **Published**: WACV2024 (Oral)
- **Code**: [Official](https://github.com/miccunifi/ARNIQA)
- **Keywords**: self-supervised; linear regression, degradation model

Thanks for your time!

**Comment by chaofengc** [comment]
Thank you so much! We appreciate your involvement and support. Your paper has been included in our repository.

Furthermore, the repo is open to any direct contributions, and we would be very thankful if you could help to add more works in the future.
