### ISSUE TITLE
Wrong author name

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [chaofengc/Awesome-Image-Quality-Assessment#9]
Hi @chaofengc!

Thanks for your awesome repo!

I am the author of the ```Arxiv 2024``` paper "_Quality-aware Image-Text Alignment for Real-World Image Quality Assessment_". You indicated "Lorenzo et al." as the author of the paper, but Lorenzo is my first name so it should be "**Agnolucci et al.**". Could you please change my name to use my last name instead of my first name?

Thanks in advance

**Comment by chaofengc** [comment]
Sorry for the mistake, I have fixed it.

**Comment by LorenzoAgnolucci** [comment]
Don't worry it is not a big deal. Than you very much for the prompt response!
